# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(data.table)
library(dplyr)
library(DT)
library(jpeg)
library(leaflet)
library(maps)
library(mongolite)
library(purrr)
library(rhino)
library(shiny)
library(shiny.fluent)
library(shiny.router)
library(shiny.semantic)
library(shinyjs)
