name: Rhino Test
on: push
permissions:
  contents: read
jobs:
  main:
    name: Run linters and tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup system dependencies
        run: |
          packages=(
            # List each package on a separate line.
            libgdal-dev
            libcurl4-openssl-dev
            libssl-dev 
            libsasl2-dev
          )
          sudo apt-get update
          sudo apt-get install --yes "${packages[@]}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup R dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Lint R
        if: always()
        shell: Rscript {0}
        run: rhino::lint_r()

      - name: Lint JavaScript
        if: always()
        shell: Rscript {0}
        run: rhino::lint_js()

      - name: Lint Sass
        if: always()
        shell: Rscript {0}
        run: rhino::lint_sass()
